<?php

namespace OSSchools\Extensions\CommonMark;

use League\CommonMark\Extension\Extension;
use OSSchools\Extensions\CommonMark\InlineParsers\AutoLinkParser;
use OSSchools\Extensions\CommonMark\InlineParsers\StrikeThroughParser;
use OSSchools\Extensions\CommonMark\InlineRenderers\ExternalLinkRenderer;
use OSSchools\Extensions\CommonMark\InlineRenderers\StrikeThroughRenderer;

class OSSchoolsCommonMarkExtension extends Extension
{
    public function getBlockParsers()
    {
        return [
        ];
    }

    public function getBlockRenderers()
    {
        return parent::getBlockRenderers(); // TODO: Change the autogenerated stub
    }

    public function getInlineProcessors()
    {
        return [
        ];
    }

    public function getInlineParsers()
    {
        return [
            new StrikeThroughParser(),
            new AutoLinkParser()
        ];
    }

    public function getInlineRenderers()
    {
        return [
            'OSSchools\\Extensions\\CommonMark\\Element\\StrikeThrough' => new StrikeThroughRenderer(),
            'League\\CommonMark\\Inline\\Element\\Link' => new ExternalLinkRenderer('localhost.net'),
        ];
    }

    public function getDocumentProcessors()
    {
        return [
        ];
    }
}