<?php

namespace OSSchools\Extensions\CommonMark;

use League\CommonMark\Extension\Extension;
use OSSchools\Extensions\CommonMark\Inline\Parsers\AutoLinkParser;
use OSSchools\Extensions\CommonMark\Inline\Parsers\StrikeThroughParser;
use OSSchools\Extensions\CommonMark\InlineRenderers\StrikeThroughRenderer;

class OSSchoolsCommonMarkExtension extends Extension
{
    public function getBlockParsers()
    {
        return [
        ];
    }

    public function getBlockRenderers()
    {
        return parent::getBlockRenderers(); // TODO: Change the autogenerated stub
    }

    public function getInlineProcessors()
    {
        return [
        ];
    }

    public function getInlineParsers()
    {
        return [
            new StrikeThroughParser(),
            new AutoLinkParser()
        ];
    }

    public function getInlineRenderers()
    {
        return [
            'OSSchools\\Extensions\\CommonMark\\Inline\\Element\\StrikeThrough' => new StrikeThroughRenderer(),
            // Need to find away to get the domain of the application easily
            //'League\\CommonMark\\Inline\\Element\\Link' => new ExternalLinkRenderer()
        ];
    }

    public function getDocumentProcessors()
    {
        return [
        ];
    }
}